### ISSUE TITLE
1.8.1 installer is detected as FileRepMalware by several anti-virus.

### ISSUE THREAD

**Issue by ljh131** [mintty/wsltty#74] opened 2017-11-20 11:35 UTC
could it be false positive?

https://www.virustotal.com/#/file/cb528e42a1924d39096880679c3bff49b28f8c60ab5dc6629fa1036d8ef513db/detection

**Comment by mintty** [comment] 2017-11-20 11:52
Duplicate of #28, #31; please report to the scan service provider.
See also #63, and #32 about signing.

**Closed by mintty** 2017-11-20 11:52 UTC
