### ISSUE TITLE
Occasionally print "[[O" or "[[I" abnormally on the screen

### ISSUE THREAD

**Issue by fengyichui** [mintty/wsltty#335] opened 2023-06-28 05:55 UTC
Hi,

When I use tmux, occasionally print "[[O" or "[[I" abnormally on the screen. And `Windows Terminal` do not has this issue.

What can I do to help this?

**Comment by mintty** [comment] 2023-06-28 09:58
These are the focus report escape sequences. They are only sent if explicitly enabled with a DECSET 1004 control sequence. If a program enables these reports and does not catch them properly, it is a bug in that program.
There may be a race condition if a program disables the reporting (and does not expect it anymore) while a report was already triggered. Please report to tmux.

**Comment by fengyichui** [comment] 2023-06-28 11:04
I have reported to tmux, and we check the debug log, tmux just received literally "[[O". The authors of TMUX think this may be a WSL bug.
I tested with `Windows Terminal` for a long time and couldn't find this issue

**Comment by mintty** [comment] 2023-06-28 18:05
So there is a tmux issue? Please provide its link.

**Comment by fengyichui** [comment] 2023-06-29 00:57
Here: https://github.com/tmux/tmux/issues/3601

**Comment by fengyichui** [comment] 2023-07-18 02:31
I use v3.2.0 cygwin1.dll, this issue doesn't seem to happen anymore. [cygwin_3.2.0.zip](https://github.com/mintty/wsltty/files/12075274/cygwin_3.2.0.zip)

**Comment by mintty** [comment] 2023-07-18 07:40
Thank you for the information, that is very interesting indeed.
I was trying to test with mintty versions before reporting to cygwin, and it's quite bothersome to set up a reliable test case for this. What is your current test scenario? How often would it happen?
Anyway, if we can establish that the issue does not occur with cygwin 3.2.0, I will prepare a report.
Would be good also to work out which cygwin version between 3.2.0 and current 3.4.7 introduced a bug.

**Comment by mintty** [comment] 2023-07-19 19:27
It does not seem to happen with the latest snapshot from http://cygwin.com/snapshots/ which is a 3.4.0 patch version.
Neither does it seem to happen with 3.5.0 which can be installed as a test version.
Please check that.

**Comment by fengyichui** [comment] 2023-07-20 02:21
I test last snapshot, this issue is happened.
I test some older snapshot: `cygwin1-20220217.dll` is bad, `cygwin1-20220127.dll` seems good:
[cygwin1-20220127-good.zip](https://github.com/mintty/wsltty/files/12101484/cygwin1-20220127-good.zip)
[cygwin1-20220217_bad.zip](https://github.com/mintty/wsltty/files/12101487/cygwin1-20220217_bad.zip)

**Comment by mintty** [comment] 2023-07-20 02:29
Hmm, so the newer one is good but the current one bad again? This does not appear consistent, maybe it's just the testing which did not expose the issue because it appears so rarely.
Testing 3.5.0 would be helpful.
I've tried to create an automatic test scenario to improve the process, which would get feedback from the tracing application to stop once the issue occurs, so you wouldn't have to fiddle interactively with that tool. But it's tricky to build something appropriate...

**Comment by fengyichui** [comment] 2023-07-20 02:36
I also tested `cygwin-3.5.0-0.341.dll`, it is bad.
It seems that since the `cygwin1-20220217.dll` version, there is a problem.
Today I'll work with version `cygwin1-20220127.dll` to see if this version is really good.

**Comment by mintty** [comment] 2023-08-06 10:13
The issue is fixed with the latest cygwin test release 3.5.0-0.370, to be released with 3.5.0 (later this year) and maybe 3.4.8 if that gets released (still unclear).

**Comment by mintty** [comment] 2023-08-21 09:30
Cygwin 3.4.8 has been released, with this fix included.

**Comment by mintty** [comment] 2023-08-21 09:31
Reopening as this is a wsltty issue, sorry. Next release to come soon.

**Comment by mintty** [comment] 2023-09-03 11:30
Released 3.6.5.

**Closed by mintty** 2023-09-03 11:30 UTC
