### ISSUE TITLE
wsltty send incorrect keycode

### ISSUE THREAD

**Issue by skywind3000** [mintty/wsltty#229] opened 2020-03-16 09:10 UTC
In a regular terminal (gnome-terminal, xterm, securecrt, xshell), Pressing both `Enter` and `Shift+Enter` will send `^M` (0x13). 

In wsltty/mintty, `Enter` sends `^M` as expected, but `Shift+Enter` sends `^J` (0x10):

![图片](https://user-images.githubusercontent.com/3035071/76738745-29b23b80-67a6-11ea-8a5f-8ad188245b46.png)

It is really annoying, sometimes people make mistake by pressing `Enter` as `Shift+Enter`:

```c
while (0) { <cursor>
```

Assuming I am editing in vim, and I type very fast, when I input a `{` and the left `shift` key is still unreleased but the `enter` key is pressed. I will get a `SHIFT+Enter`, and wsltty sends a `^J` to my vim, `^J` has been mapped to `switching window` in both normal and insert mode:

```VimL
inoremap <c-h> <esc><c-w>h
inoremap <c-j> <esc><c-w>j
inoremap <c-k> <esc><c-w>k
inoremap <c-l> <esc><c-w>l
```

So if I press `SHIFT+Enter` in vim, vim recognize it as `CTRL+J` and trigger the window switching command.

`gnome-terminal` sends `^M` for shift+enter:

![图片](https://user-images.githubusercontent.com/3035071/76740050-30da4900-67a8-11ea-99ef-d2e20033294d.png)

`SecureCRT` sends `^M` for shift+enter:

![图片](https://user-images.githubusercontent.com/3035071/76740140-5e26f700-67a8-11ea-8d42-0d93b4ed8f53.png)

Windows cmd terminal:

![图片](https://user-images.githubusercontent.com/3035071/76740316-a9d9a080-67a8-11ea-98ce-cdf8feb6bfcd.png)

I won't make any mistake in those terminals, but in wsltty, sending `^j` for `Shift+Enter`  is really frustrating.

**Comment by mintty** [comment] 2020-03-16 12:21
No need to boost this report with tons of screenshots.
Mintty sends ^J for Shift+Enter, some other terminals don't.
Duplicate of mintty/mintty#977.

**Closed by mintty** 2020-03-16 12:21 UTC

**Comment by skywind3000** [comment] 2020-03-16 12:41
Sorry for duplication, I didn't know if this issue (or question) should be in wsltty or mintty.
