### ISSUE TITLE
wsltty does not work if user profile folder has a space in it

### ISSUE THREAD

**Issue by ryancdotorg** [mintty/wsltty#105] opened 2018-06-07 17:21 UTC
My user profile folder is `C:\Users\Ryan Castellucci`

When I start wsltty, I very briefly see a console window showing

```
wslbridge error: failed to start backend process
note: backend error output: /bin/bash: /mnt/c/Users/Ryan: No such file or directory
```

**Comment by Biswa96** [comment] 2018-06-07 19:14
Duplicate of #49. See last three comments. Solved in wslbridge.

**Comment by mintty** [comment] 2018-06-07 20:01
The fixed version is not part of the current wsltty release yet, however.
The next release is in planning, it can only be a matter of weeks :/ (or maybe sooner).

**Comment by mintty** [comment] 2018-07-01 23:37
Released 1.9.0 with updated wslbridge which should fix this.

**Closed by mintty** 2018-07-01 23:37 UTC
