### ISSUE TITLE
WSLTTY closes immediately after launch

### ISSUE THREAD

**Issue by masterfink** [mintty/wsltty#112] opened 2018-06-26 16:53 UTC
Anytime that I launch wsltty it immediately closes. I am launching the shortcuts from the Start Menu. I have tried launching Ubuntu Terminal, WSL Terminal, Ubuntu Terminal % and WSL Terminal %.

**Comment by Biswa96** [comment] 2018-06-26 17:44
Find the `mintty.exe` in AppData\Local\wsltty folder and open it with command `mintty.exe -WSL -h always`. You can see the error and reply it.

**Comment by masterfink** [comment] 2018-06-27 01:30
My profile is my first name and last name "C:\Users\First Last". The error says "note: backend error output: /bin/bash: /mnt/c/Users/First: No such file or directory". Looks like it can't recognize the space in between my first and last name

**Comment by Biswa96** [comment] 2018-06-27 03:48
This is duplicate of #105

**Comment by mintty** [comment] 2018-07-01 23:37
Released 1.9.0 with updated wslbridge which should fix this.

**Closed by mintty** 2018-07-01 23:37 UTC
