### ISSUE TITLE
3.1.0.2 broke input for radare2

### ISSUE THREAD

**Issue by GustavoLCR** [mintty/wsltty#216] opened 2019-12-28 14:22 UTC
You can test with:
```
r2 -
[0x00000000]>
```
You should be able to write in commands then, but nothing happens

It works fine with 3.1.0

**Comment by Biswa96** [comment] 2019-12-28 15:24
Can you do this test with the newer one? Download cygwin from this link[1]. Extract `cygwin1.dll` from it using `tar -xf` command. Place it in `C:\Users\X\AppData\Local\wsltty\bin` folder (assume `X` is your user name).

**Comment by Biswa96** [comment] 2019-12-28 15:25
Can you do this test with the newer one? Download [cygwin-3.0.7-1.tar.xz][1]. Extract `cygwin1.dll` from it using `tar -xf` command. Place it in `C:\Users\X\AppData\Local\wsltty\bin` folder (assume `X` is your user name).

[1]: http://cygwin.mirror.constant.com/x86_64/release/cygwin/cygwin-3.0.7-1.tar.xz

**Comment by GustavoLCR** [comment] 2019-12-28 15:58
> Can you do this test with the newer one? Download [cygwin-3.0.7-1.tar.xz](http://cygwin.mirror.constant.com/x86_64/release/cygwin/cygwin-3.0.7-1.tar.xz). Extract `cygwin1.dll` from it using `tar -xf` command. Place it in `C:\Users\X\AppData\Local\wsltty\bin` folder (assume `X` is your user name).

That fixed it, thanks!

**Comment by mintty** [comment] 2019-12-28 16:01
So what kind of program is radare? Windows program, Linux program? Some basic information is necessary to assess the situation because reverting to cygwin 3.0.7 is a workaround, not a fix.

**Comment by GustavoLCR** [comment] 2019-12-28 16:03
> So what kind of program is radare? Windows program, Linux program? Some basic information is necessary to assess the situation because reverting to cygwin 3.0.7 is a workaround, not a fix.

Its a linux program

**Comment by mintty** [comment] 2020-01-20 11:42
Please provide a reproducible test case:
What WSL distro? How to install radare2?

**Comment by mintty** [comment] 2020-02-17 16:01
Closing due to missing demonstration of an issue.

**Closed by mintty** 2020-02-17 16:01 UTC
