### ISSUE TITLE
1.8.4 issues

### ISSUE THREAD

**Issue by vadimkantorov** [mintty/wsltty#92] opened 2018-02-13 11:43 UTC
1. I'm using ssh + screen + vim combo. Then sometimes WSLtty get in a state when it can't be closed either by clicking the Close cross in top-right or from Windows taskbar context menu. The terminal is still active.

2. It sometimes gets confusing stty cols and rows and vim screws up.

Downgrading to 1.8.2 is a workaround.

**Comment by mintty** [comment] 2018-02-13 14:12
I'm not aware of any change since 1.8.2 that would explain either 1. or 2.
1.: With option "Prompt about running processes on close", does the confirm popup appear? Closing problems caused by ssh are no unknown, by the way.
2.: What does "confusing" mean? What precisely happens?

**Comment by vadimkantorov** [comment] 2018-02-13 14:40
1. No pop up has appeared. I was trying to close the terminal by clicking in the cross or by clicking close in the context menu from the windows taskbar. None worked, from balky I closed the terminal by typing Ctrl+D a few times. I am not sure if ssh is to blame or not, this just happened while I was within ssh and screen.

2. Confusing means that vim won’t open full screen (even though the terminal is full screen) and won’t use full screen estate, and editing/viewing gets out of sync. “reset” command didn’t help. Entering a new ssh session didn’t help. Maybe something about SIGWINCH got changed.

I’ve downgraded to 1.8.2 for now.

**Comment by mintty** [comment] 2018-02-13 15:50
2. How do you start mintty? Do you start it fullscreen or switch later? Do you run it on your primary monitor (the one with the taskbar) and do you have your taskbar in "auto-hide" mode? What does ``stty size` say? Any other particular specialty that might have impact...?

**Comment by vadimkantorov** [comment] 2018-02-13 16:38
2. With wsl.bat. Then I connect to ssh, then I maximize it usually. On the primary monitor, no auto-hide. I'll check `stty size` and will let you know.

**Comment by mintty** [comment] 2018-02-13 16:47
That's a delicate workflow. I wouldn't bet that ssh reliably propagates screen size changes. Why don't you maximize first, then run ssh? Does that make a difference?

**Comment by vadimkantorov** [comment] 2018-02-13 16:56
It has always worked well with 1.8.2 (and it does work well once I downgraded).

I remember vaguely having tried maximizing first and then opening vim, but I'll double check and will let you know.

**Comment by mintty** [comment] 2018-02-14 21:02
I've replayed your test case description: wsl.bat, ssh, Alt+Enter for fullscreen, `stty size` - it reports the correct full screen terminal size.
I can only close this issue because it has no reproducible test case, and also no meaningful title, by the way.

**Closed by mintty** 2018-02-14 21:02 UTC

**Comment by vadimkantorov** [comment] 2018-02-14 22:44
In my case it was wsl.bat + ssh + _screen_ + vim. I'll update this issue when I upgrade back to 1.8.4 (for now I'm using the open terminals).

Sorry, I should have created two separate issues. Then proper titles are easy to come up with.

**Comment by mintty** [comment] 2018-02-14 22:54
I've tried both ssh + fullscreen + screen or ssh + screen + fullscreen, stty size always adapts. What ssh version, server kind, 'screen' version do you run? The same for both test cases?

**Comment by vadimkantorov** [comment] 2018-02-15 12:46
I've upgraded back to 1.8.4 and cannot reproduce the issues anymore. I will keep using it and will let you know if I have these issues again.
