### ISSUE TITLE
.minttyrc themes don't work

### ISSUE THREAD

**Issue by pcroland** [mintty/wsltty#256] opened 2020-09-13 18:50 UTC
Every theme I tried just worked as base16:
![image1](https://widevine.is-a.fail/jlmD3U.png)

**Comment by mintty** [comment] 2020-09-14 02:10
Duplicate of #251. Fixed in mintty.

**Comment by mintty** [comment] 2020-10-24 15:34
Released 3.4.1.

**Closed by mintty** 2020-10-24 15:34 UTC
