### ISSUE TITLE
Cursor stops blinking after entering vim/tmux

### ISSUE THREAD

**Issue by mktange** [mintty/wsltty#133] opened 2018-10-25 23:14 UTC
Hey. I just installed wsltty and noticed that whenever I enter a program such as vim or tmux, my cursor will stop blinking:

![wsltty-cursor-blink](https://user-images.githubusercontent.com/3582986/47535337-08039c00-d8b3-11e8-9547-c823ad5242a9.gif)

Any idea what could be causing this? 

I am only seeing this happen when using wsltty. It works fine when running WSL normally, or even when running WSL via Git Bash's mintty/winpty.

Thanks in advance!

**Comment by mintty** [comment] 2018-10-26 00:58
Which version of mintty do you run?
Probably duplicate of mintty/mintty#787.

**Comment by mintty** [comment] 2018-10-26 01:52
Please check which escape sequences your application uses as configured when starting, or make a terminal log (not screenshot) that includes the effect, so it can be reproduced with `cat log`.

**Comment by mktange** [comment] 2018-10-26 10:21
Here is a [log file of it happening](https://github.com/mintty/wsltty/files/2518786/log.txt). Doing `cat log.txt` makes the cursor stop blinking for me.

**Comment by mktange** [comment] 2018-10-26 10:42
Tried doing `cat log.txt` in Git Bash as well, and it also made the cursor stop blinking. However, now this issue is now also happening when opening vim in Git Bash... not sure what has changed since I last tried it there, besides me restarting my computer. 

Just to try something else, I tried opening the terminals in ConEmu, and here it currently still works correctly in Git Bash, but not wsltty. When doing `cat log.txt` it stops the cursor from blinking in wsltty, while with Git Bash it keeps blinking, but seems to partially mess up the terminal output.

**Comment by mintty** [comment] 2018-10-26 10:54
The culprit is the CSI escape sequence `ESC[?12l` which is supported since 2.9.0, following xterm.
It is included in the terminfo "cnorm" sequence to reset the cursor. Somebody probably put it in there on purpose.

**Comment by mintty** [comment] 2018-10-26 18:50
Actually, behaviour is identical in xterm; this is not a mintty issue, so I'm marking it invalid.
A workaround is already available: include option `SuppressDEC=12` in your config file.
Maybe I'll add a specific hint to the wiki, leaving the issue open for now.

**Comment by mktange** [comment] 2018-10-27 10:31
Awesome, that worked. Thank you for the fast troubleshooting and help!

**Comment by JonnyRa** [comment] 2019-02-12 10:06
For anyone else who stumbles across this, I think this might be a neovim issue.  I used it instead of normal vim to trial floobits recently, environment was gnome-shell + tmux.  I lost cursor blink in my whole tmux session accross all panes and windows and restarting tmux had no effect... nvim had told me to muck around with some tmux settings so it took me a while to realise that it was also disabled in the parent terminal.  Closing the parent terminal and reopening (+ not using neovim!) resolved the issue for me.

**Comment by mintty** [comment] 2019-02-15 11:46
It also happens with non-neo vim. With most applications, it's not caused by the appliction itself but the underlying terminal library (often ncurses), as explained above.
Remedy also as explained above, and it's mentioned meanwhile in the wiki, so I'm closing the issue.

**Closed by mintty** 2019-02-15 11:46 UTC
Labels: invalid, question

**Comment by mintty** [comment] 2019-04-23 21:14
Actually there is one possible workaround that I've now implemented:
Blinking cursor mode (DECSET 12) effectively overlays blinking cursor style (DECSCUSR) so that DECRST 12 does not reset blinking but revert to the previous blinking style.

**Comment by mintty** [comment] 2019-05-28 06:52
Released 3.0.1.
