### ISSUE TITLE
3.0.5 instantiated 'bash' not classified as a login shell on 'Debian' and 'Ubuntu18.04' --

### ISSUE THREAD

**Issue by aabatpurdue** [mintty/wsltty#191] opened 2019-10-01 23:49 UTC
$ shopt login_shell
login_shell     off

Oops.

-- Thanks for the app,
--    Paul Townsend

**Comment by Biswa96** [comment] 2019-10-02 03:36
Try to append a `-l` (small L) option after the command.

**Comment by ratinoxone** [comment] 2019-10-02 13:45
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~`
Can't append "-l" to bash.exe because the shortcut isn't invoking bash.exe. wsltty/mintty does that underneath. Or it should and it was up until two days ago.

**Comment by mintty** [comment] 2019-10-02 13:57
To start a login shell, append a single "-" argument to the invocation command:
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~ -`

**Comment by ratinoxone** [comment] 2019-10-02 14:03
> To start a login shell, append a single "-" argument to the invocation command:
> `%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~ -`

Confirmed this works.

Which leaves me and probably many others wondering why such a significant change happened in a minor point release with no warning and no documentation on the front page.

**Comment by mintty** [comment] 2019-10-02 14:09
There was no change. The "-" parameter for WSL has been supported since wsltty 1.8.2 and is a documented mintty parameter.

**Comment by mintty** [comment] 2019-10-02 14:13
Admittedly, it was not documented for wsltty explicitly. Updated.

**Comment by Biswa96** [comment] 2019-10-02 14:13
From [`man bash`][1]:

> A login shell is one whose first character of argument zero is a `-` or one started with the `--login` option.

[1]: http://man7.org/linux/man-pages/man1/bash.1.html#INVOCATION

**Comment by ratinoxone** [comment] 2019-10-02 15:12
> Admittedly, it was not documented for wsltty explicitly. Updated.

> From [`man bash`](http://man7.org/linux/man-pages/man1/bash.1.html#INVOCATION):
> > A login shell is one whose first character of argument zero is a `-` or one started with the `--login` option.

I think you're both missing the point: wsltty's default behavior changed from login to not-login without warning or explanation in a minor point release. This is a bug that should be fixed.

**Comment by mintty** [comment] 2019-10-02 15:33
As I said, there was no such change. The Start menu shortcuts and the installed desktop shortcuts or previous versions have all been non-login. The reason was that WSL distributions, when invoked the built-in way, used to be non-login, too. This seems to have changed recently, so it's to be reconsidered.

**Comment by ratinoxone** [comment] 2019-10-02 16:36
> As I said, there was no such change. The Start menu shortcuts and the installed desktop shortcuts of previous versions have all been non-login. The reason was that WSL distributions, when invoked the built-in way, used to be non-login, too. This seems to have changed recently, so it's to be reconsidered.

I am running the same Debian 10 today that I was running yesterday. I am running the same OS build 18362.356 today that I was running yesterday. I was running wsltty 3.0.2.3 as a login shell by default yesterday; I am running wsltty 3.0.5 as a non-login shell by default today. Something changed in wsltty somewhere. Two of us so far have reported this behavior. If this behavior is not intended then it's a bug that needs to be identified and fixed. If this behavior is intended then it should have been in a major point release (ie, a 3.1) and documented in the release notes because it is a significant change in behavior.

**Comment by mintty** [comment] 2019-10-02 18:08
Unfortunately, I cannot reproduce your claim anymore as the previous wsltty versions stopped working on my system a while ago for unknown reason. Anyway, it had not been intended to invoke WSL in login mode, which is consistent with the instructions on the project page to add login mode. If your WSL was previously invoked in login mode, *that* was the bug, and 3.0.5 is the fix :)
@Biswa96, are you aware of any change from wslbridge to wslbridge2 that may have caused this confusion?

**Comment by Biswa96** [comment] 2019-10-03 03:54
@mintty once you told not to enable login option by default, here https://github.com/Biswa96/wslbridge2/issues/6. And yes login mode shouldn't be enable always, it is users' choice.

**Comment by Biswa96** [comment] 2019-10-03 03:55
@mintty once you told not to enable login option by default, here https://github.com/Biswa96/wslbridge2/issues/6. And yes login mode shouldn't be enabled always, it is users' choice. Also the guide is now in Readme page in wsltty.

**Comment by ratinoxone** [comment] 2019-10-03 04:44
@Biswa96 are you being deliberately obtuse? I didn't enable login by default. That was wsltty's own default behavior and it suddenly changed **WITHOUT WARNING**.

@mintty I maybe narrowed it down to WSL generate shortcuts. Running 3.0.5 with the WSL Terminal shortcut from 3.0.2.5 exhibits the old behavior (starts a login shell). After running 3.0.5's WSL generate shortcuts the WSL Terminal shortcut exhibits the new behavior (starts a non-login shell).

**Comment by Biswa96** [comment] 2019-10-03 04:49
> I didn't enable login by default.

I know that and I confirmed it in my previous comment. Yes, the default behavior is changed in new wslbridge2. The login mode is not enabled by-default, user has to do it, which you did confirm by adding a `-` in command line.

**Comment by mintty** [comment] 2019-10-03 09:03
> Running 3.0.5 with the WSL Terminal shortcut from 3.0.2.5 exhibits the old behavior (starts a login shell).

Please quote the target command line of your old-behaviour shortcut here, or upload the shortcut.

**Comment by ratinoxone** [comment] 2019-10-03 14:00
Target from 3.0.2.3 (not 3.0.2.5; that's a typo) with login shell behavior:
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty"`

Target from 3.0.5 before running WSL Generate Shortcuts with login shell behavior:
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty"`

Target from 3.0.5 after running WSL Generate Shortcuts with non-login shell behavior:
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty"`

As you can see, the shortcut target does not change. It's something underneath but whatever that something is, it's tripped by running WSL Generate Shortcuts.

**Comment by mintty** [comment] 2019-10-03 14:29
This is mysterious, and I cannot reproduce it.
Please upload the shortcut file that invokes 3.0.5 in login mode for you (rename it to add a filename suffix that is accepted on github).

**Comment by ratinoxone** [comment] 2019-10-03 18:10
Then we're at an impasse because you have everything I have. My shortcut files don't change between versions. What changes is whatever processing WSL Generate Shortcuts does.

**Comment by mintty** [comment] 2019-10-03 18:31
> you have everything I have

No, I don't have a login-mode invocation setup. If you have one, you should provide it here as best as possible. Otherwise I can only close the issue as there is no reproducible test case.
If you'd ask to change the behaviour, please open another issue.

**Comment by aabatpurdue** [comment] 2019-10-03 20:15
Sorry for not getting back here sooner.

I have been flipping between installations of 3.0.5 and 3.0.2.3.  There are no other changes to the OS or anything else being made.  The login_shell value is consistently off and on, respectively.

I did note a second difference.  The value of the SHLVL environment variable is 2 and 3, respectively.

Attached is a copy of two shortcut invocations, the top one for 3.0.5 and the second one for 3.0.2.3.
[ubuntushortcut.txt](https://github.com/mintty/wsltty/files/3687849/ubuntushortcut.txt)
I note that they both have **-~** as the last characters.


--  Thanks,
--    Paul Townsend

**Comment by mintty** [comment] 2019-10-03 20:29
(If you use login_shell to test whether you're in a login shell, you could more easily add an echo to your ~/.profile.)
The SHLVL thing might be an interesting observation, on the other hand it is not set by every shell.
Do your startup profile scripts make any decision based on SHLVL?
Anyway, I cannot analyse this further unless you provide a *reproducible test case*, so I'm asking, now for the third time, to provide your shortcut file that would start a login shell.

**Comment by ratinoxone** [comment] 2019-10-03 23:24
My WSL Terminal %.lnk as created by wsltty 3.0.2.3 renamed .txt and dragged over. This shortcut opens a login shell (shopt login_shell returns on).
[WSL Terminal %.txt](https://github.com/mintty/wsltty/files/3688408/WSL.Terminal.txt)

**Comment by mintty** [comment] 2019-10-04 12:52
That shortcut does not start a login shell here.

**Comment by ratinoxone** [comment] 2019-10-04 13:47
> That shortcut does not start a login shell here.

I told you it wasn't the shortcut:
> As you can see, the shortcut target does not change. It's something underneath but whatever that something is, it's tripped by running WSL Generate Shortcuts.

**Comment by aabatpurdue** [comment] 2019-10-04 19:56
@mintty From the text of your comment of Oct 3 4:29 EDT I did not send what you asked for.  What exactly do you require?  See comment immediately preceding yours.

Do I use SHLVL.  No - it will work with Cygwin (SHLVL=1) to determine a login shell but not with WSL.

Strange thought.  Is there a sequence of 2 or 3 'bash' invocations that causes the SHLVL value to increase?

--  Thanks,
--    Paul Townsend

**Comment by Biswa96** [comment] 2019-10-04 20:02
`SHLVL` is always One (1) in WSL realm. Try only wsl.exe.

**Comment by mintty** [comment] 2019-10-04 20:37
The file you uploaded is what I requested but it does not start a login shell here (reproduced your further description, fresh installation).
Please analyse whether something in your startup scripts may invoke another shell level.
Please also add an `echo something` to your WSL ~/.profile (or .bash_profile if you have), to be sure.

**Comment by mintty** [comment] 2019-10-06 15:47
Released 3.0.6. Keeping the previous non-login behaviour for now.

**Closed by mintty** 2019-10-06 15:47 UTC

**Comment by mintty** [comment] 2019-12-02 15:41
Released 3.1.0.
