### ISSUE TITLE
terminal hangs sometimes

### ISSUE THREAD

**Issue by Mehtabuddin** [mintty/wsltty#7] opened 2016-09-30 08:36 UTC
I was using wsltty and sometimes either after the first command I typed or even a few commands in mintty, the console would freeze when I pressed enter and basic commands like "ls" would freeze.

I removed the .minttyrc file and everything went back to normal I thought, but I later just kept typing "ls" and "make" in a directory without a makefile over and over and eventually the console froze.

A bunch of zsh processes, bash, and wsltty backend processes are growing in my task manager because when it freezes and I close it, it doesn't kill the process

**Comment by mintty** [comment] 2016-09-30 09:54
So if you now start from the desktop shortcut, without a .minttyrc file in %LOCALAPPDATA%/wsltty/home/%USERNAME%, you still experience freezing?

**Comment by Mehtabuddin** [comment] 2016-09-30 18:05
Ok I continued to test this problem and it isn't the minttyrc, to reproduce this problem try:

"ls" 5 times
"make" in a directory without a Makefil 2-3 times
"cd" into another directory
"ls" a few times
"make" a few times

Mintty seems to freeze after I get an stderr but I don't know what the culprit is. Once it does freeze, opening another terminal will freeze much sooner and more and more zsh and wsltty processes populate task manager.

**Comment by mintty** [comment] 2016-09-30 21:30
Cannot reproduce. What does `type make` report?
What are the precise symptoms of "freezing"? Do the menus still open? Can you enter a character? Does Windows shade out the window?

**Comment by Mehtabuddin** [comment] 2016-09-30 23:14
make is /usr/bin/make

Ok so I did some further testing, I restarted my computer and opened up bash with mintty and I couldn't reproduce the problem with the steps I listed.

However when I opened a second mintty while the other was open, I was able to reproduce the problem on the second mintty and any more that I opened after (even if I closed the ones open)

When it freezes I can still move the window, the cursor still blinks, but any input I give doesn't show up. The freeze generally happens when I hit enter.

**Comment by rprichard** [comment] 2016-10-01 00:32
FWIW, I've noticed a bug where the WSL tty system seems to freeze up.  I haven't tried reporting it, but I just confirmed that it still reproduces in Win10 14393.  I used a WSL xterm connected to a Cygwin X server.  In the xterm, I ran `find /`, while holding down the Enter key.  After a second or two, the output froze, and when I tried to start an unrelated instance of `bash.exe`, it never printed the bash prompt.  The xterm window didn't repaint when I resized it, and I couldn't close it.  It looks like I'll have to reboot...  I post a link here if I file a proper report.

**Comment by rprichard** [comment] 2016-10-01 01:16
I found a couple of issues that might be related:
 
 - https://github.com/Microsoft/BashOnWindows/issues/1127#issuecomment-249619931
 - https://github.com/Microsoft/BashOnWindows/issues/1085

**Comment by Mehtabuddin** [comment] 2016-10-01 04:18
I want to say this is zsh but zsh works fine in windows CMD

I also had the problem where the prompt never gets printed after it freezes for the first time.

I am on build 14936

**Comment by mintty** [comment] 2016-10-01 09:05
Thanks, Ryan, for the references. So this issue could be closed here; but I'll leave it open for information until the WSL base issue is reported fixed.

**Comment by fpqc** [comment] 2016-10-07 21:27
Fixed.

**Comment by mintty** [comment] 2016-11-16 15:14
Can anyone report on this issue?

**Comment by fpqc** [comment] 2016-11-16 16:33
@mintty The fix came in 14961.

**Comment by mintty** [comment] 2016-11-16 16:51
Thanks.

**Closed by mintty** 2016-11-16 16:51 UTC
