### ISSUE TITLE
Mintty show the warning font not found, using system substitute =0

### ISSUE THREAD

**Issue by DavichiHug** [mintty/wsltty#151] opened 2019-02-15 16:17 UTC
font not found, using system substitute =0

![snipaste_2019-02-16_00-11-16](https://user-images.githubusercontent.com/23614846/52869178-0ae70d00-3180-11e9-8316-dc11cfb74529.png)

i try to set other fonts but it's doesn't work.

**Comment by mintty** [comment] 2019-02-15 16:40
Duplicate of #87.
It's a bug of the application (or a plugin) sending a wrong escape sequence.
Workaround: `mintty -o SuppressOSC=50`.

**Comment by mintty** [comment] 2019-02-15 16:46
> It's a bug of ... a plugin

Likely eslint, which has fixed the bug meanwhile. Please update.

**Comment by victorhcm** [comment] 2019-03-04 02:45
> `mintty -o SuppressOSC=50`

This one has fixed the issue for me, just add it to the program launcher: 

![image](https://user-images.githubusercontent.com/3802222/53707532-243db980-3e0e-11e9-932d-623b8fe1e4a5.png)

**Closed** 2019-06-05 09:53 UTC
Labels: invalid
