### ISSUE TITLE
wsltty not starting a login shell

### ISSUE THREAD

**Issue by ramsay-jones** [mintty/wsltty#70] opened 2017-11-15 21:15 UTC
First let me say that wsltty makes WSL usable - it was awful trying to use Ubuntu in the console!
However, one minor issue that I noticed was that, when launching mintty from the menu item, the
shell does not execute either .bash_profile or .profile. At the moment, I have to remember to source
my .bash_profile by hand each time. (I prefix ~/bin to $PATH, among other things, in .bash_profile).

**Comment by mintty** [comment] 2017-11-15 22:06
Duplicate of #56. It depends on wslbridge.
@rprichard?

**Comment by mintty** [comment] 2017-12-16 22:24
Released 1.8.2 which should be starting a login shell.

**Closed by mintty** 2017-12-16 22:24 UTC

**Comment by mintty** [comment] 2018-02-07 16:54
... actually it doesn't; previous comment still applies

**Comment by mintty** [comment] 2019-12-02 15:41
Released 3.1.0.
