### ISSUE TITLE
WSL Terminal always closes immediately - How to debug

### ISSUE THREAD

**Issue by kmille** [mintty/wsltty#156] opened 2019-02-27 08:26 UTC
Hey,

my WSL Terminal always closes immediately after starting it and I don't know why or how to debug it. I used wsltty-1.9.6-install.exe to install it. I use the Ubuntu 18.04 Image from the Windows Store on a Windows 10 Laptop.

That's how I call it:
H:\>%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~ -V

The config file in "%APPDATA%\wsltty" is emtpy. Can you please help me. I can't go back to the default shell

**Comment by mintty** [comment] 2019-02-27 08:32
See the mintty manual page:
`-V`
Print version information and exit.
Why did you add that option?

**Comment by kmille** [comment] 2019-02-27 08:37
Hey
that was just a test. I normally run in it without the -V so just
%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~

**Comment by mintty** [comment] 2019-02-27 08:52
Add option `Hold=always` to the config file.

**Comment by kmille** [comment] 2019-02-27 13:04
sry for the late response:
%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~ -h=always 
Should be the same behaviour like using the config.
But I tried this. No error message for me. The window is just closing again...

**Comment by mintty** [comment] 2019-02-27 13:46
On the command line, the option is `-h always` without a `=`.

**Comment by kmille** [comment] 2019-02-27 14:24
![unbenannt](https://user-images.githubusercontent.com/6470600/53497128-cb83bf00-3aa3-11e9-801c-43f542d08cbc.PNG)

**Comment by mintty** [comment] 2019-02-27 14:35
Sure I like closed issues :) but that does not look like a solution for you‽

**Comment by kmille** [comment] 2019-02-27 14:44
You are right. Sorry

**Comment by kmille** [comment] 2019-03-01 10:40
Hey, it's working again. And I don't know why 😄 
Probably Windows domain foo magic or Windows Updates ...

thanks for your support!

**Comment by kmille** [comment] 2019-03-14 09:06
hm the problem occurs again -:-
Any ideas what to do with an immediately closing WSL Terminal?

**Comment by mintty** [comment] 2019-03-14 11:38
We've had the `Hold` option already, at least it should not close then. You should see some error message or other trace of what happens.
Is this related to #153, #152? Maybe #135? Or rather #142?

**Comment by mintty** [comment] 2019-03-14 11:51
Did you change the WSL mount path configuration? The solution for #91 might not be sufficient...

**Comment by kmille** [comment] 2019-03-17 07:55
I will try it and give you feedback

**Comment by jrhorn424** [comment] 2019-03-21 02:29
I can connect to other distros fine, but not Alpine.

![image](https://user-images.githubusercontent.com/388761/54730496-abee2c80-4b5f-11e9-94c1-38ee79668a6e.png)

**Comment by mintty** [comment] 2019-03-21 08:28
Reproduced, also when using wslbridge directly from cygwin.
Navigating to /mnt/c/Users/.../wsltty/bin and trying to run wslbridge-backend directly also fails with `./wslbridge-backend: not found`. That's weird; maybe Alpine has a safety policy not to run programs from Windows mounts?
To test the latter assumption, I tried to copy wslbridge-backend into Alpine's /bin but that fails for permission right, also Alpine does not seem to support `sudo` - maybe it's a "closed shop"?

**Comment by Biswa96** [comment] 2019-03-21 08:45
@jrhorn424 From where did you download Alpine?

**Comment by mintty** [comment] 2019-03-21 11:36
Even though the backend Makefile contains options `-static-libgcc -static-libstdc++` already?

**Comment by Biswa96** [comment] 2019-03-21 14:14
OK, I explain. When I compiled `wslbridge-backend` in Debian based distributions `readelf -d wslbridge-backend` shows:

```
Dynamic section at offset 0xd2898 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libutil.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```
Now in Alpine, I did this:

* Update & upgrade: `apk update; apk upgrade`
* Install bash because `bash` is hard coded in wslbridge: `apk add bash bash-completion binutils`
* Install pro tools: `apk add alpine-sdk build-base gcc g++ make`
* Apply this [StackOverflow answer](https://stackoverflow.com/a/41956165/8928481) because MUSL has issue with `strerror_r()`.
* BOOM!

**Comment by Biswa96** [comment] 2019-03-21 14:14
OK, I explain. When I compiled `wslbridge-backend` in Debian based distributions `readelf -d wslbridge-backend` shows:

```
Dynamic section at offset 0xd2898 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libutil.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```
Now in Alpine, I did this:

* Update & upgrade: `apk update; apk upgrade`
* Install bash because `bash` is hard coded in wslbridge: `apk add bash bash-completion binutils`
* Install pro tools: `apk add alpine-sdk build-base gcc g++ make`
* Apply this [StackOverflow answer](https://stackoverflow.com/a/41956165/8928481) because MUSL has issue with `strerror_r()`.
* Make `/bin/bash` default in `/etc/passwd`.
* Compile `wslbridge-backend` in Alpine.
* BOOM!

**Comment by jrhorn424** [comment] 2019-03-22 16:32
Thank you, that works for me as well! Very much appreciated.

**Comment by kmille** [comment] 2019-03-25 18:01
I still don't get it. It seems like the wslbridge is the problem. I use Terminus at the moment but it's pretty buggy if I use it with tmux. Should I ask at the wslbridge repo?

**Comment by mintty** [comment] 2019-03-25 18:42
I've tried to follow Biswa's suggestion and compile wslbridge-backend in Alpine (commented out the strerror stuff) - with no success. You can report it to wslbridge but I wouldn't expect a solution in wslbridge itself (except for the strerror).

**Comment by Biswa96** [comment] 2019-03-25 19:22
@kmille's issue is different that @jrhorn424. @kmille is using Ubuntu.

**Comment by mintty** [comment] 2019-03-25 19:57
OK, right, I overlooked the bash thing in your comment. Got it working.
Then I tried to compile statically again, with the error
`wslbridge-backend.cc:(.text.startup+0x115b): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking`
This is strange. Anyway, I disabled the getpwuid part and, with `-static` added to the backend Makefile, it works, i.e. wslbridge-backend compiled with gcc (in "normal" WSL, not Alpine). I could also reenable the strerror stuff. So there is in fact an opportunity to cover Alpine with a common wslbridge-backend binary, if only we find a solution for the getpwuid crap.

And, for that matter, this is not the original issue opened here, but that was fuzzy anyway...

**Comment by Biswa96** [comment] 2019-03-25 21:09
> wslbridge-backend.cc:(.text.startup+0x115b): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

@mintty That is known issue. See here https://github.com/rprichard/wslbridge/issues/26

**Comment by mintty** [comment] 2019-03-27 07:53
I've tried to load getpwuid with dlopen but it did not work...

**Comment by kmille** [comment] 2019-04-05 09:00
In the mantime: I works again #yail \o/
I still have no clue but I'm sure it's not a problem of mintty. It's probably caused by our domain foo. Thanks it adavance!

**Comment by mintty** [comment] 2019-04-30 20:44
While the original problem (@kmille) may be a different issue,
I think the Alpine/wslbridge-backend binary compatibility issue is solved by patching wslbridge-backend.
I'll apply a patch that implements getpwuid directly by reading /etc/passwd, so static compilation will work.

**Comment by Biswa96** [comment] 2019-05-02 17:39
Isn't static compiling made it bigger binary file? And what is the difference between your patch and glibc implementation of getpwuid?

**Comment by mintty** [comment] 2019-05-03 02:26
Size is ~1.7MB rather than 150KB. But it works.
My getpwuid only checks /etc/passwd while there are other authentication mechanisms (network/domain controlled).

**Comment by mintty** [comment] 2019-05-28 06:59
Released 3.0.1.

**Comment by mintty** [comment] 2019-05-28 17:52
Reopened with 3.0.1.2, see #169.

**Comment by mintty** [comment] 2019-06-05 09:49
Are there any other distributions that have this problem? If it's only Alpine, we could add an alternative, Alpine-compiled wslbridge-backend to the package, and make a choice based on the selected distribution.

**Comment by itsjef** [comment] 2019-07-12 04:23
> Are there any other distributions that have this problem? If it's only Alpine, we could add an alternative, Alpine-compiled wslbridge-backend to the package, and make a choice based on the selected distribution.

I am having the same issue with both Ubuntu 18.04.02 LTS and Debian

**Comment by mintty** [comment] 2019-07-12 04:46
With Ubuntu, it's more likely #171. Please check your WSL version (1 or 2) for the distribution.

**Comment by itsjef** [comment] 2019-07-12 04:56
@mintty My WSL version is 1, I'm also not participating in Windows Insiders anyway.

**Comment by Biswa96** [comment] 2019-07-12 05:05
It may be helpful if wsltty makes `-h always` a default option.

**Comment by itsjef** [comment] 2019-07-12 07:53
Hmm I also added `-h always` but only got a blank window 🤔 

![image](https://user-images.githubusercontent.com/1902587/61111842-b2a90280-a4b4-11e9-9d5f-285c9fc39927.png)

**Comment by mintty** [comment] 2019-07-12 08:32
I've installed Ubuntu 18.04 LTS and Debian, run Start Menu → WSLtty → configure WSL shortcuts,
and it works for me.

**Comment by mintty** [comment] 2019-07-12 08:34
Maybe there are other Windows/WSL changes, applicable to WSL version 1, that impede WSLtty function?
Which version do you run?

**Comment by itsjef** [comment] 2019-07-12 11:12
@mintty I ran Start Menu → WSLtty → configure WSL shortcuts for both version 3.0.1 and 3.0.1.2 and the problem still occured

**Comment by itsjef** [comment] 2019-07-13 15:11
Is there a way I can create a crash log and upload it here so you guys can look into the issue? I think that will help.

**Comment by mintty** [comment] 2019-07-13 15:33
Do you see a file `wslbridge.exe.stackdump` in either your %USERPROFILE%, %LOCALAPPDATA%\wsltty or %LOCALAPPDATA%\wsltty\bin folders? If there is one, we can try to set up something to debug it.

**Comment by itsjef** [comment] 2019-07-14 03:13
@mintty I don't, is there a option to turn on stack dump?

**Comment by mintty** [comment] 2019-07-14 04:33
If there is no crash happening, that would not help. It seems rather that either the wslbridge frontend or backends is stalled.

**Comment by mintty** [comment] 2019-07-14 17:41
You can install a cygwin environment (https://cygwin.com/setup-x86_64.exe).
Then, in a cygwin terminal, copy `cp $LOCALAPPDATA/wsltty/bin/wslbridge* /bin`.
Invoke `mintty --WSL` manually, from a cygwin shell.

**Comment by itsjef** [comment] 2019-07-15 04:30
I did it but the terminal still closed immediately. 🤔

**Comment by mintty** [comment] 2019-07-15 05:47
> closed immediately

You said before you get a blank window. That's not the same symptom. Any output if you force it to stay open with `mintty -h alw --WSL`?

**Comment by itsjef** [comment] 2019-07-15 07:53
When I ran `mintty -h alw --WSL`, a blank window appeared, if I drop the `-h alw` then it would close immediately.

**Comment by itsjef** [comment] 2019-07-15 08:31
I'm thinking it's a `wslbridge` issue. I have tried using [_goreliu/wsl-terminal_](https://github.com/goreliu/wsl-terminal) but the window also opens and closes at once.

**Comment by mintty** [comment] 2019-07-15 09:11
> I'm thinking it's a wslbridge issue.

I thought so already but I have no idea how to proceed with analysis, remotely.

> Occasionally the window will stay open ...

Oh. Well, WSL sometimes needs a while until startup has settled. If you only wait enough...?

**Comment by itsjef** [comment] 2019-07-15 09:16
> I thought so already but I have no idea how to proceed with analysis, remotely.

There is no way to export a dump file too, so sad...

> Oh. Well, WSL sometimes needs a while until startup has settled. If you only wait enough...?

My computer has been running 4 days straight, that must be enough startup time 😞

**Comment by mintty** [comment] 2019-07-15 09:26
As I asked the original poster earlier:
Did you change the WSL mount path configuration? The solution for #91 might not be sufficient...

**Comment by itsjef** [comment] 2019-07-15 11:20
I didn't. I don't even have a `/etc/wsl.conf` file. All of my configurations are default.

I tried creating an empty `/etc/wsl.conf` file but it didn't have any effect.

**Comment by cakira** [comment] 2019-07-23 20:41
**I've just hacked a solution!** 

**Problem**
My wsltty used to work great until I tried (unsuccessfully) using Docker for Windows Desktop. After I installed docker, my WSL Terminal started closing immediately. The symptoms are identical to the ones described by the OP.


**My setup**
Windows 10 Pro, Version 1709 - I have administrative rights only on demand
wsltty v3.0.2 installed via [Chocolatey](https://chocolatey.org/)
Ubuntu 18.04
Docker for Windows Desktop (version 2.0.0.31259, I guess) - currently uninstalled


**My workaround**
A created a file `%LOCALAPPDATA%\wsltty\bin\wslbridge-hack.bat` with the following contents:
`@%LOCALAPPDATA%\wsltty\bin\wslbridge.exe -t -e APPDATA -C~`
Then I changed the WSL Terminal shortcut to:
`C:\Users\cakira\AppData\Local\wsltty\bin\mintty.exe --configdir="C:\Users\cakira\AppData\Roaming\wsltty" -~ "C:\Users\cakira\AppData\Local\wsltty\bin\wslbridge-hack.bat"`


**Tests I did before finding the workaround**
I tried uninstalling, reinstalling, wsltty with chocolatey, without success.
I tried installing an old version (1.9.6) without chocolatey, without success.
I tried reinstalling Ubuntu, several times, both with and without reboots between uninstall and installs
I tried opening mintty in a CMD window. It opened a new window, with the message "... Failed to run /bin/bash..."
I tried openint mintty with `mintty.exe cmd.exe`. It opened a new window, with the windows command prompt, as expected.
I tried openint mintty with `mintty.exe notepad.exe`. It opened a new window, then a new notepad window, as expected.
I tried opening wslbridge with the command 'wslbridge.exe'. The bash prompt appeared in the same window, as expected.
I tried opening mintty with `mintty.exe .\wslbridge.exe`. It opened a new window then immediately closed it. I believe this is exactly the problem.
I created a .bat file wslbridge-hack.bat, with the content `@%LOCALAPPDATA%\wsltty\bin\wslbridge.exe` and executed `mintty.exe .\wslbridge-hack.bat`. A new window was opened, with the bash prompt! Hooray! 🎉

Then I customized wslbridge-hack.bat, until it was similar to the original shortcut. The solution is the workaround presented above.

**Notes**
I saw no wslbridge.exe.stackdump file anywhere.
Now, I have a side effect of a new window asking for confirmation when I click in the Terminal window close button.

**Comment by tynanbe** [comment] 2019-07-24 16:10
See https://github.com/mintty/wsltty/issues/169#issuecomment-514691889 for a possible fix for musl-based distros (Alpine, Void-musl, etc.).

**Comment by itsjef** [comment] 2019-07-29 03:07
@cakira I got this message when running your workaround before window closed itself.

```
wslbridge warning: GetVersionEx reports version 6.2 -- is wslbridge.exe properly manifested?
```

**Comment by cakira** [comment] 2019-07-29 12:05
Hi @itsjef !
I'm not sure about what is happening in your case. I guess our problems are different.
If I open a CMD window and execute `%LOCALAPPDATA%\wsltty\bin\wslbridge.exe` the bash prompt is shown in the current window. Does this happen to you too?

For reference, if I execute `%LOCALAPPDATA%\wsltty\bin\mintty.exe --version` and `%LOCALAPPDATA%\wsltty\bin\wslbridge.exe`, the results are, in order: _mintty 3.0.2 (x86_64-pc-cgwin - wsltty 3.0.2_ and _wslbridge 0.2.5-dev_

**Comment by itsjef** [comment] 2019-07-30 07:22
Hi @cakira, this is the output when I ran those commands. 

![image](https://user-images.githubusercontent.com/1902587/62108699-e5386500-b2d4-11e9-887a-af941ca44066.png)

For `%LOCALAPPDATA%\wsltty\bin\mintty.exe --version`, a window popped up showing the mintty.exe's version. `%LOCALAPPDATA%\wsltty\bin\wslbridge.exe --version` worked fine too. However `%LOCALAPPDATA%\wsltty\bin\wslbridge.exe` as showed.

**Comment by mintty** [comment] 2019-07-30 07:29
> `%LOCALAPPDATA%\wsltty\bin\wslbridge`

Works here. The message probably is a result of wslbridge-backend failing to run a shell.
Which wsltty version was that? Do you have the capability to compile wslbridge-backend and add some debug stuff?

**Comment by itsjef** [comment] 2019-07-30 08:08
> Which wsltty version was that?
I'm using 3.0.2 

I will try to complie wslbridge-backend myself and report later

**Comment by itsjef** [comment] 2019-07-30 08:19
@mintty I compiled `wslbridge-backend` myself, this time `%LOCALAPPDATA%\wsltty\bin\wslbridge` worked. However when I double-clicked on the WSL Terminal shortcut - modified following to @cakira's workaround - it still closed immediately with the same `wslbridge warning: GetVersionEx reports version 6.2 -- is wslbridge.exe properly manifested?` message.

**Comment by mintty** [comment] 2019-07-30 10:34
Can you also compile the frontend (cygwin environment needed)?
Try to set up unconditional usage of output pipe, in line 1204:
```
-    if (windowsVersion() >= std::make_tuple(10u, 0u, 15063u)) {
+    if (1 || windowsVersion() >= std::make_tuple(10u, 0u, 15063u)) {
```

**Comment by itsjef** [comment] 2019-07-30 11:30
@mintty I compiled the frontend after modifying the condition and replaced the the `%LOCALAPPDATA%\wsltty\bin\wslbridge`. The window still closed right after I opened it.

**Comment by itsjef** [comment] 2019-08-14 09:14
When I tried running `wslbridge.exe -t -e APPDATA -C ~` from CMD, I would be prompted with a Bash shell as the WSL opened successfully. However, when I created a `wslbridge.bat` file with that line as its content, then double-clicked to open it, a window would appear and close immediately, just like when I clicked on the `WSL Terminal.lnk` shortcut.

Strange thing is, occasionally, the window wouldn't close and there would be a Bash shell as if no error happened.

Noted that then I ran the `wslbridge.bat` file from CMD/Powershell, it would work all the time.

I wonder if there is a relationship between this behavior and the issue we are discussing?

I'm using WSLtty version 3.0.2.3, fresh installation, by the way.

**Comment by mintty** [comment] 2019-08-14 10:33
> I wonder if there is a relationship between this behavior and the issue we are discussing?

Probably yes, so thanks for your observations.

**Comment by takamiyoshi** [comment] 2019-08-30 01:10
Hi guys,

I am suffering from the similar symptoms that the window opened and closed immediately in wsltty, currently 3.0.2.3. I started with the 3.0.0 version a few month ago, then it worked fine a while. Now It did not. I reinstalled 3.0.0 and even 1.9.X, but all versions showed the same symptoms. 

From my observation, the "TrendMicro Virus Buster (Internet security)" did something wrong. When I stopped the virus buster, wsltty launched as I expected. Any idea to fix?
 
@cakira I tried your suggestions, but it did not change at all.
My Linux distribution is Ubuntu 18.04

**Comment by itsjef** [comment] 2019-08-30 02:59
@takamiyoshi Wow, I'm having Trend Micro Security Agent on my machine too. Sadly, I can't uninstall or stop it due to company policy.

**Comment by takamiyoshi** [comment] 2019-08-30 03:10
I asked my company to test if Trend Micro was the reason. Same situation, I can not uninstall/stop it for my work.  Interestingly, it worked before with Trend Micro, but now not. I do not know when the symptom started. 

I have found the post, and it said "exclusion of scanning" might resolve the issue. Then I tried on my computer to set exclusion of scanning at the directory %LOCALAPPDATA%\wsltty, not successful. Also our IT did something on their side (not really sure what they did), not successful. 

During the re-installing process of Trend Micro, I had the instance without Trend Micro, then it worked fine!!..

So stressful.

**Comment by cakira** [comment] 2019-09-01 15:31
Hi!
My new workmate also have this problem and [my solution](https://github.com/mintty/wsltty/issues/156#issuecomment-514375453) didn't work for him too. :-(
He started using [cmdr](https://cmder.net/) instead, and I even tried it for the sake for uniformity, but cmdr is not my thing.

I can confirm that we have Trend Micro Security Agent too, but I have not the permission to unload it.
And in my computer, wsltty is working steady after applying my solution.

**Comment by Biswa96** [comment] 2019-09-08 09:41
I have some opinions here https://github.com/Biswa96/wslbridge2/issues/4. Can you guys provide your opinions which is better (or worse)?

**Comment by MarkFiveThousand** [comment] 2019-09-09 23:42
Does it strike anyone else as odd that the message below that is supposed to contain the substring '/bin/bash' is getting overwritten with random data.  This smells like a memory overwrite error in wslbridge.  That would jive with the intermittent nature of the problem in addition to reports of other people having similar difficulties with wslbridge used in other apps.

C:\Users\mhodges\AppData\Local\wsltty\bin>wslbridge.exe
error: could not exec '/b□/□$': No such file or directory

C:\Users\mhodges\AppData\Local\wsltty\bin>wslbridge.exe
error: could not exec '/b□□': No such file or directory

**Comment by mintty** [comment] 2019-09-10 05:18
Thanks for the observation. It seems wslbridge is not maintained anymore, but the next wsltty release will switch to wslbridge2.

**Comment by mintty** [comment] 2019-10-01 23:09
Released 3.0.5.

**Comment by mintty** [comment] 2019-10-01 23:09
Tentatively closing.

**Closed by mintty** 2019-10-01 23:09 UTC

**Comment by cakira** [comment] 2019-10-14 16:21
Hi!
Just to report, I upgraded my Windows 10 from 1703 to 1903 and upgraded wsltty to version 3.0.6, via chocolatey. At first, it worked flawlessly. Then, after 3 ou 4 days, it reverted to the buggy behavior of closing by itself.

I tried to investigate, but I was discouraged when I saw that a command that worked once stopped working after just a few minutes. I'll try investigating again in a couple days.

**Comment by Biswa96** [comment] 2019-10-14 17:05
What command did you try? Try to wsltty with a fresh installed distribution.

**Comment by mintty** [comment] 2019-10-14 17:22
Is that with WSL 2? (Output of `wsl -l -v`)
Closing by itself means: immediately, after clicking the desktop shortcut?
If you add a `-h alw` option to the shortcut target, any diagnostic information? What version does Options - About report in that case?

**Comment by cakira** [comment] 2019-10-15 14:17
I'm using WSL 1, since WSL 2 isn't available to my Windows version (Windows 1903 Build 18362).
I tried to repeat my own procedure [above](https://github.com/mintty/wsltty/issues/156#issuecomment-514375453) and it didn't work because _sometimes_ wslbridge2.exe just returned, silently, as below:

```
C:\Users\cakira>%LOCALAPPDATA%\wsltty\bin\wslbridge2.exe

C:\Users\cakira>
```

and sometimes it started a WSL session, as below (I use the [fish shell](https://fishshell.com/) in my WSL):
```
C:\Users\cakira>%LOCALAPPDATA%\wsltty\bin\wslbridge2.exe
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira  
```

So, I wrote a script just to have an idea of how often wslbridge2 works. The batch script is:
```
@ECHO ON
@set count=0
:loop
@set /a count=%count% + 1
@echo wslbridge2 test count: %count%
@%LOCALAPPDATA%\wsltty\bin\wslbridge2.exe
@goto loop
```
And the results are:
```
C:\Users\cakira>%LOCALAPPDATA%\wsltty\bin\retry.bat
wslbridge2 test count: 1
wslbridge2 test count: 2
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira 
wslbridge2 test count: 3
wslbridge2 test count: 4
wslbridge2 test count: 5
wslbridge2 test count: 6
wslbridge2 test count: 7
wslbridge2 test count: 8
wslbridge2 test count: 9
wslbridge2 test count: 10
wslbridge2 test count: 11
wslbridge2 test count: 12
wslbridge2 test count: 13
wslbridge2 test count: 14
wslbridge2 test count: 15
wslbridge2 test count: 16
wslbridge2 test count: 17
wslbridge2 test count: 18
wslbridge2 test count: 19
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira 
wslbridge2 test count: 20
wslbridge2 test count: 21
wslbridge2 test count: 22
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira 
wslbridge2 test count: 23
wslbridge2 test count: 24
wslbridge2 test count: 25
wslbridge2 test count: 26
wslbridge2 test count: 27
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira 
wslbridge2 test count: 28
wslbridge2 test count: 29
wslbridge2 test count: 30
wslbridge2 test count: 31
wslbridge2 test count: 32
wslbridge2 test count: 33
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira 
wslbridge2 test count: 34
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira 
wslbridge2 test count: 35
wslbridge2 test count: 36
wslbridge2 test count: 37
wslbridge2 test count: 38
wslbridge2 test count: 39
wslbridge2 test count: 40
wslbridge2 test count: 41
wslbridge2 test count: 42
wslbridge2 test count: 43
wslbridge2 test count: 44
wslbridge2 test count: 45
wslbridge2 test count: 46
wslbridge2 test count: 47
wslbridge2 test count: 48
wslbridge2 test count: 49
wslbridge2 test count: 50
wslbridge2 test count: 51
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira 
wslbridge2 test count: 52
wslbridge2 test count: 53
wslbridge2 test count: 54
wslbridge2 test count: 55
wslbridge2 test count: 56
wslbridge2 test count: 57
wslbridge2 test count: 58
Welcome to fish, the friendly interactive shell⏎
/m/c/U/cakira  
``` 
_(I formated a little the results above, just to fit the screen and I also typed CTRL-D after every WSL session)_

I guess my next step should be compiling wslbridge2 and debugging it, but I'm afraid of installing cygwin, cygwin gcc and everything. 

As a side note, I tried to use Windows Terminal, but mintty is still the best, by far!

**Comment by Biswa96** [comment] 2019-10-15 14:43
> sometimes wslbridge2.exe just returned, silently

* Did you try with other fresh installed distribution in WSL?
* Did you try to change the default shell in WSL?
* What theme or extension are you using in `zsh`?

**Comment by mintty** [comment] 2019-10-15 15:44
You are not supposed to run wslbridge2 from a Windows cmd console session, that's not its purpose.
You could simply call `wsl` in that case, without mintty of course.
Or you can invoke mintty (via its wsltty installation) and it will implicitly involve wslbridge2.

**Comment by cakira** [comment] 2019-10-15 16:16
> > sometimes wslbridge2.exe just returned, silently
> 
>     * Did you try with other fresh installed distribution in WSL?

No, I didn't try a fresh install since my upgrade to Windows 1903 last week. Reinstalling and reconfiguring the distribution isn't a light operation to me and when I tried it in July, it didn't change anything regarding wsltty.

>     * Did you try to change the default shell in WSL?

I've just tried to change the default shell back to bash. The buggy behavior persists with bash.

>     * What theme or extension are you using in `zsh`?

I don't use zsh. I use fish shell.

**Comment by Biswa96** [comment] 2019-10-15 16:22
Oh, mistake, I mean did you install any theme in fish shell? 

> Reinstalling and reconfiguring the distribution isn't a light operation to me

You can install any distribution without using Windows Store, just for a test. There are many here in GitHub. I have tested wslbridge2 with Debian, Ubuntu, Alpine with zsh, fish, bash etc without any error.

**Comment by cakira** [comment] 2019-10-15 16:34
> You are not supposed to run wslbridge2 from a Windows cmd console session, that's not its purpose.

Thank you for your attention. In this case, I was just trying to troubleshoot my buggy instance of wsltty, the same way as [I did in July](https://github.com/mintty/wsltty/issues/156#issuecomment-514375453).

My tests point that mintty is just fine, but wslbridge2 only works about 15% of the times it is executed.

> Or you can invoke mintty (via its wsltty installation) and it will implicitly involve wslbridge2.

Yep! And it will fail most of the time. (If I add `-h alw` to the shortcut target, mintty opens with no contents)
However, as a quick (and very very dirty 🙈) fix, I changed my batch script to execute mintty (with the same parameters as the shortcut) several times. Most of the executions will fail, but one or another will succeed and open the mintty terminal as intended.

**Comment by cakira** [comment] 2019-10-15 17:06
> You can install any distribution without using Windows Store, just for a test. There are many here in GitHub. I have tested wslbridge2 with Debian, Ubuntu, Alpine with zsh, fish, bash etc without any error.

I tried Debian right now and it had the same behavior as Ubuntu: it opens only once in a few tries.

> Oh, mistake, I mean did you install any theme in fish shell?

Not a theme, but I use [fish-prompt-metro](https://github.com/fishpkg/fish-prompt-metro) and it includes some Unicode characters in my prompt, similar to [Powerline](https://github.com/powerline/powerline).

**Comment by cakira** [comment] 2019-10-15 17:28
> You can install any distribution without using Windows Store, just for a test. There are many here in GitHub. I have tested wslbridge2 with Debian, Ubuntu, Alpine with zsh, fish, bash etc without any error.

I tried Debian right now and it had the same behavior as Ubuntu: it opens only once in a few tries.

> Oh, mistake, I mean did you install any theme in fish shell?

Not a theme, but I use [fish-prompt-metro](https://github.com/fishpkg/fish-prompt-metro) and it includes some Unicode characters in my prompt, similar to [Powerline](https://github.com/powerline/powerline).

**Comment by Biswa96** [comment] 2019-10-15 18:03
I have tested your setup with newly installed Debian and Ubuntu without any error. Just one difference. I am using Windows 10 Fast Insider builds (not 1903). Anyone can suggest code fix in wslbridge2 repository for this issue.

**Comment by mintty** [comment] 2019-10-16 06:17
So maybe we need to raise the Windows Build prerequisite? And wsltty could revert to wslbridge(1) for earlier versions, i.e. still for the current official, non-insider Windows release (which doesn't support WSL V2 yet, I think)?

**Comment by Biswa96** [comment] 2019-10-16 13:08
Wait 1 day. PC issue. I'll test it in a VM.

**Comment by cakira** [comment] 2019-10-16 16:06
For reference, I uninstalled wsltty 3.0.6 and tried version 1.9.6, that I used a long time ago.
Version 1.9.6 had the same behavior as 3.0.6: `%LOCALAPPDATA%\wsltty\bin\wslbridge.exe` fails silently most of the time, but once in a while, it opens the shell.

By the way, my wsltty used to work like a breeze some time ago. Then I tried to install docker for windows in my computer and that screwed up my wsltty.

**Comment by Biswa96** [comment] 2019-10-17 12:48
I have tested wsltty in a fresh installed Windows 10 1903 VM with fresh Debian from Windows Store, no packages are added or updated. It works flawlessly. Contributions are always welcomed in wslbridge2.

**Comment by seandex** [comment] 2019-10-22 01:02
All of sudden after (possibly) windows update.

From Bitdefender
The file F:\wsl-terminal\open-wsl.exe is infected with Gen:Suspicious.Cloud.1.cr0@aeOKczpi and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by cakira** [comment] 2019-10-22 04:22
Hello!
Just to give a feedback on my problem (the terminal closes immediately most of the time, but not always):
After debugging, I found that the problem is in [wslbridge2](https://github.com/Biswa96/wslbridge2).
In tag v0.4, the file [wslbridge-backend.cpp](https://github.com/Biswa96/wslbridge2/blob/8f05552e0e306d3a6f172e77dac6af9b3ff699f4/wslbridge/wslbridge-backend.cpp#L47) contains the function below:
```
static int connectSocket(int port) {
    const int s = socket(AF_INET, SOCK_STREAM | SOCK_CLOEXEC, 0);

    const int flag = 1;
    const int nodelayRet = setsockopt(s, IPPROTO_TCP, TCP_NODELAY, &flag, sizeof(flag));
    assert(nodelayRet == 0);

    sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    const int connectRet = connect(s, reinterpret_cast<const sockaddr*>(&addr), sizeof(addr));
    assert(connectRet == 0);

    return s;
}
```

If the function `connect(s, reinterpret_cast<const sockaddr*>(&addr), sizeof(addr));` executes [when port = outputSocketPort](https://github.com/Biswa96/wslbridge2/blob/v0.4/wslbridge/wslbridge-backend.cpp#L58), most of the times wslbridge will crash, even thought connect() returns zero.

I will open an issue in wslbridge2 to ask if someone could help me further debug this issue.

Thank you very much for your support!

**Comment by Biswa96** [comment] 2019-10-22 04:55
I can not reproduce the error. Can you get the error code? Just add a line `fatalPerror("connect");` in between connect and assert.

> I will open an issue in wslbridge2 to ask if someone could help me further debug this issue.

Always welcome. But need another one case of this same error.

**Comment by mintty** [comment] 2019-10-22 06:35
@seandex, this is twofold the wrong issue to report your case. This is not the wsl-terminal project and this issue is not about virus reports.

**Comment by seandex** [comment] 2019-10-22 17:33
> @seandex, this is twofold the wrong issue to report your case. This is not the wsl-terminal project and this issue is not about virus reports.

oooops, i deleted the post. I apologize!

**Comment by iverdr17** [comment] 2020-03-09 15:51
try by uninstalling using cmd administrator and reinstalling
wsl --unregister Ubuntu-18.04

**Comment by DanKaplanSES** [comment] 2023-11-22 22:19
This would've saved me a minute or two: You put the `-h always` **before** the last argument. e.g., `%LOCALAPPDATA%\wsltty\bin\mintty.exe --tabbar=4 --WSL="Ubuntu" --configdir="%APPDATA%\wsltty" -h always -`

The first few comments make it seem like you can put `-h always` at the end, but that doesn't work.

Anyway, now that I can read the error message ("...WSL 2 requires an update to its kernel component..."), should I remove the `-h always` or leave it there?

**Comment by Biswa96** [comment] 2023-11-23 04:06
> Anyway, now that I can read the error message ("...WSL 2 requires an update to its kernel component...")

Please use the WSL from Microsoft Store or from here https://github.com/microsoft/WSL/releases

**Comment by DanKaplanSES** [comment] 2023-11-23 04:56
> > Anyway, now that I can read the error message ("...WSL 2 requires an update to its kernel component...")
> 
> Please use the WSL from Microsoft Store or from here https://github.com/microsoft/WSL/releases
> 
> In newer version of Windows, the Linux kernel binary was removed. Hence, that error message.

 I have been using the Microsoft store version for months and this just happened today. I think it may have been corrupted from my computer crashing a couple days ago. Uninstalling WSL and then manually installing the upgrade from With a Lincoln that error message fixed the issue for me.

**Comment by nullromo** [comment] 2024-10-04 15:58
This issue popped back up for me yesterday. The program closes straight away, but I can still access WSL through Windows Terminal. I also tried re-running the WSLTTY installer, but it didn't seem to help.
