### ISSUE TITLE
Error: Font not found, using system substitute

### ISSUE THREAD

**Issue by abjugard** [mintty/wsltty#87] opened 2018-01-25 14:24 UTC
I'm encountering the following error in wsltty whenever I get an error from ESLint. It does not happen when running wsl.exe, only in wsltty.

![image](https://user-images.githubusercontent.com/287697/35392537-7f77c85e-01e2-11e8-86d0-b7deaa655d60.png)

Any ideas what could be causing this? The blurred out text is just the rest of the current working directory.

I'm using Fira Code Retina in wsltty, but it doesn't seem to make much of a difference, as I get this error no matter what font I select in wsltty.

**Comment by mintty** [comment] 2018-01-25 14:40
`CurrentDir=...` is not a font name, there must be something very weird going on. Please upload your config file. Did you select the font with the terminal Options menu?

**Comment by abjugard** [comment] 2018-01-25 14:53
Yes I did, here is my [.minttyrc](https://gist.github.com/abjugard/449c3bef7af88cbb15e75151fbfb1dee) file. (Located on my disk at %APPDATA%/mintty/config)

**Comment by mintty** [comment] 2018-01-25 15:29
Please provide more information: mintty version (from Options... About), environment (cygwin, msys, ...), exact way of invocation (command line, shortcut, ...).

**Comment by abjugard** [comment] 2018-01-29 10:08
Version: wsltty 1.8.3.2
Environment: WSL
Invocation: Shortcut with:
- Target: `%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~ `
- Starting directory: `%USERPROFILE%`

**Comment by mintty** [comment] 2018-01-29 12:51
There must be somthing corrupted in your installation. Did you get the installation archive from the github repository? Can you reinstall?

**Comment by mintty** [comment] 2018-02-06 12:14
Any new insights? Otherwise I intend to close the issue as it seems to be a singular problem.

**Comment by abjugard** [comment] 2018-02-12 07:18
Sorry for the long wait, been away this week. This still happens with 1.8.4. Yes I get my installation archives from the github releases page.

The exact command I'm running is `webpack --config build/webpack.lib.conf.js --watch --progress --hide-modules` and the error happens if ESLint spits out an error. It seems no matter what the program is doing it shouldn't be causing issues with wsltty fonts though.

**Comment by mintty** [comment] 2018-02-12 07:56
As I have no idea what ESLint is, I overlooked this detail in your post report.
So this does not happen when mintty starts, but later when you run this command in it, right?
The only explanation is that mintty receives the escape sequence to switch a font dynamically, and that sequence is malformed (because "CurrentDir=..." is not a font name). To verify, please switch on logging before you start the command (and off after the error occurs) and provide the log, or check it yourself for an escape sequence beginning ESC]50.

**Comment by mintty** [comment] 2018-03-08 12:37
Closing for missing evidence. If the issue persists, you can still provide a log file as requested.

**Closed by mintty** 2018-03-08 12:37 UTC

**Comment by gartnera** [comment] 2018-03-17 19:39
I've attached a log of this error. It seems to occur for the first time on line 44 of the log.

I can reproduce it by running `echo -e "\033]50;CurrentDir=/home/alex/test\007"`

For reference this output is generated on line 248 in this file: [eslint-friendly-formatter/index.js](https://github.com/royriojas/eslint-friendly-formatter/blob/master/index.js#L248). I temporarily fixed it by removing the '\u0007' on that line.

I don't know much about terminal escape codes, but does sending a bell there even makes sense?

[log.txt](https://github.com/mintty/wsltty/files/1821953/log.txt)

**Comment by mintty** [comment] 2018-03-18 09:58
The sequence is clearly defined (as of xterm) to change the font, and the BEL is part of it. There is no CurrentDir=... in its syntax. Also I don't see how it should be sent from a JS script to a terminal, but if that's somehow part of the function of that script, the script is broken here. Please report it to the as a bug.

**Comment by mintty** [comment] 2018-09-14 07:06
That means the configured font (Source Code Pro) is not installed on your system, which is not a surprise after a Windows reset. Install the font or choose another one from the Options menu.

**Comment by oshihirii** [comment] 2018-09-14 07:10
@mintty - thanks so much, installed it from here and the message went away! 

https://www.fontsquirrel.com/fonts/source-code-pro

**Comment by krubokrubo** [comment] 2018-12-15 22:13
I had the same problem using ESLint in an ssh session from Cygwin. It turns out this is caused by [a bug in the eslint-friendly-formatter module](https://github.com/royriojas/eslint-friendly-formatter/issues/30) which has been fixed in version 4. (You can check your version using `npm list eslint-friendly-formatter`.) The problem was solved by updating eslint-friendly-formatter to version 4:

`npm install eslint-friendly-formatter@4`
