### ISSUE TITLE
Symlinked home directory seems to be handled incorrectly since wslbridge2

### ISSUE THREAD

**Issue by SimonPilkington** [mintty/wsltty#205] opened 2019-11-16 21:52 UTC
I have my home directory symlinked to a location outside the WSL filesystem. This worked fine until wsltty started using wslbridge2; now the symlink is apparently resolved, and thus I end up in the symlink destination instead of ~ when starting wsltty.

Moreover
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
     PATH="$HOME/bin:$PATH"
fi
```
in .profile acts as if $HOME/bin does not exist, even though it does. This also worked correctly before wslbridge2.

I am using 1809.

**Comment by mintty** [comment] 2019-11-16 22:23
For the second issue, what does `echo ~ $HOME` say?
For the first, @Biswa96, any idea why wslbridge2 resolves the home directory?

**Comment by SimonPilkington** [comment] 2019-11-16 22:27
`echo ~ $HOME` produces identical results (the home directory as set in passwd) as expected. The incorrect result is only produced during startup. If I `. .profile` after startup, it works correctly. I believe both issues are the same issue.

**Comment by Biswa96** [comment] 2019-11-17 05:52
wslbridge2 backend uses [wordexp(3)][1] to resolve current working directory path. I can not reproduce your issue with the latest wslbridge2 master branch in latest Windows 10 Insider build. I have tried by making `/home/user` symlinked with `/mnt/c/folder`.

BTW, can you try to add this patch in wslbridge2 repository and build mintty and wslbridge2 to test?
[wslbridge2-backend-chdir-test.patch.txt](https://github.com/mintty/wsltty/files/3855270/wslbridge2-backend-chdir-test.patch.txt)


[1]: http://man7.org/linux/man-pages/man3/wordexp.3.html

**Comment by SimonPilkington** [comment] 2019-11-17 12:36
Unfortunately I see no changes with the patch applied.

I did some testing, and a login shell does not have the issue. That is `.\wslbridge2.exe -l -W ~` works correctly while `.\wslbridge2.exe -W ~` has the issue as described.

(Using a login shell solves both issues.)

**Comment by mintty** [comment] 2019-11-17 13:07
The next wsltty release shall use login mode anyway.
However, it would still be interesting to identify the cause.
You said `. .profile` does the adjusting. Can you track step-by-step which of the commands in .profile does it effectively, please? Do you have a `cd` in there?

**Comment by SimonPilkington** [comment] 2019-11-17 13:34
Actually, I just remembered .profile is not executed for non-login shells, so if wsltty currently doesn't spawn a login shell, this is the expected result. Yet it worked before the switch to wslbridge2, which would indicate wsltty spawned a login shell then. Can you confirm this?

**Comment by Biswa96** [comment] 2019-11-17 13:36
Previous wslbridge always use login mode.

**Comment by Biswa96** [comment] 2019-11-17 13:36
Previous wslbridge use login mode by default.

**Comment by Biswa96** [comment] 2019-11-17 13:37
Previous wslbridge use login mode by default. To use login mode, just append a dash `-` after the command line in wsltty shortcut.

**Comment by SimonPilkington** [comment] 2019-11-17 13:40
Okay, mystery solved, although we don't know why non-login shells have trouble with symlinked home directories. It could also be a problem in bash I suppose. Feel free to close this issue if you believe it is unrelated to wsltty or wslbridge2.

**Comment by mintty** [comment] 2019-11-17 15:04
I reproduced the effect with Debian, but sourcing .profile does not fix it for me.

**Comment by SimonPilkington** [comment] 2019-11-17 17:43
Sourcing .profile should only fix ~/bin not being added to PATH. It does not fix the current directory issue.

**Comment by Biswa96** [comment] 2019-12-06 13:20
Now wsltty uses login shell by default. This issue may be closed.

**Comment by mintty** [comment] 2019-12-06 14:00
To be verified. In addition to the statement above
> don't know why non-login shells have trouble with symlinked home directories

I would not know why login shells should *not* have the same trouble.

**Comment by SimonPilkington** [comment] 2019-12-09 13:15
Verified. 3.1.0 does not have this issue anymore, although the issue returns as expected if a non-login shell is used.

**Comment by mintty** [comment] 2019-12-09 13:46
It might be interesting to find the cause, still.
Which shell do you use? What if you use another shell?
If you start non-login, facing the effect, and `source .profile`, what happens?
...?

**Comment by SimonPilkington** [comment] 2019-12-09 13:54
Shell is whatever bash version is packaged in Debian testing. I talked about sourcing .profile above. I might try another shell sometime to see what happens. I don't have time right now.

**Comment by mintty** [comment] 2020-10-24 16:28
Closing as outdated.

**Closed by mintty** 2020-10-24 16:28 UTC
