### ISSUE TITLE
Text and Font properties crashes when attempting to select font

### ISSUE THREAD

**Issue by valeryan** [mintty/wsltty#27] opened 2017-02-23 04:09 UTC
I am using wsltty 0.7.4 on the latest windows insider preview. When I open the options menu and try to open the font dialog on the text and font properties tab using the select button the terminal crashes. All of the other settings in the option dialog work for me.

**Comment by mintty** [comment] 2017-02-23 07:09
So the font chooser does not even open, it crashes before?
Have you made any changes to the configuration? Please provide your config file.
Can you add option `-o OldFontMenu=yes` to your mintty invocation, please?

**Comment by mintty** [comment] 2017-02-23 21:02
same with Windows PuTTY (64 bit)

**Comment by valeryan** [comment] 2017-02-24 00:39
The font dialog flashes on the screen and then it crashes just as is starts to display content. 

I assume the contents of the .minttyrc is what you are referring to for config. I am not sure where else to look. Here is whats in my .minttyrc file `Columns=125Rows=40`

I added the OldFontMenu to my invocation and it still crashes when opening the font dialog. `%LOCALAPPDATA%\wsltty\bin\mintty.exe --wsl -o Locale=C -o Charset=UTF-8  -o OldFontMenu=yes /bin/wslbridge -t /bin/bash` 

Let me know if you need any additional information from me. I don't know if there is some way to get any debug information out of terminal. 

Thanks

**Comment by mintty** [comment] 2017-02-24 19:42
Have you set any localization (Options – Window – UI language)? Any problems with the colour chooser?
Would you be able to compile a mintty repository version in a Cygwin 32-bit environment and substitute that in your wsltty hierarchy? Otherwise I'll have to add some debugging stuff to the next release.

**Comment by mintty** [comment] 2017-02-26 16:46
Unzip the debug version from the attach zip archive.
Replace your %LOCALAPPDATA%\wsltty\bin\mintty.exe with it (make a backup copy first).
Open a Windows cmd console (Win+R, enter cmd).
cd %LOCALAPPDATA%\wsltty
set MINTTY_DEBUG=h
Start mintty, either with one the wsl*.bat scripts, or manually (minimal parameters for convenience):
bin\mintty /bin/wslbridge
Try to open the font chooser (Select...)
In your cmd window, go to the Temp folder:
cd %TEMP%
Here you should see a file mintty.debug
Attach it here, please.

Also, try MINTTY_DEBUG=x or (again) -o OldFontMenu=1.

[mintty-debug.zip](https://github.com/mintty/wsltty/files/802092/mintty-debug.zip)

**Comment by valeryan** [comment] 2017-02-26 16:50
Thanks, I'll give that a try this evening when I can get on my PC.

**Comment by valeryan** [comment] 2017-03-01 22:15
So, I installed the current version of windows 10 and the font dialog loads fine but the sample text may be to the problem with insider preview. It looks like you might have some bad encoding on the text maybe. 

screenshot:

![font-sample](https://cloud.githubusercontent.com/assets/1508761/23483824/1407e0dc-fe9a-11e6-81da-41d2855b67ec.png)

**Comment by mintty** [comment] 2017-03-01 23:40
No, that's actually the font sample I selected on purpose, to collect some archetypical design properties for display and the availability of typographical quotes and €.
If you think the font sample is not good, I'll consider to change it. Maybe to a localized sentence (it's localizable anyway).

**Comment by valeryan** [comment] 2017-03-02 02:18
I have no problem with the string, however my though is that maybe the latest build of windows is not displaying that string correctly and that might be leading to the crash. If you want to compile a bin like you did before with a simple string as the example I will try it out for you. It's a wild guess but you never know.

**Comment by kylemacfarlane** [comment] 2017-03-02 05:41
I had the same problem. The solution seems to be to select the font and size you want but don't click any of the "apply" buttons. The changes are still applied even if you don't "apply" them.

**Comment by mintty** [comment] 2017-03-02 08:17
You can either "Apply" in the font chooser, or "OK" here and "Apply" or "Save" in the Options dialog.
But I think we're seeing different problems here. For @valeryan, the font menu was not even opening, while a crash on "Apply" had been previously reported (mintty/mintty#533), if that's what you are facing.

@valeryan, thanks for the log file, 4 days ago, I must have overlooked it, sorry, will check.

**Comment by mintty** [comment] 2017-03-02 08:51
I'd appreciate if you run two more tests with the attached version, please.
Both with `set MINTTY_DEBUG=h` (as before) and `set MINTTY_DEBUG=hn` (add 'n').
[mintty-debug.zip](https://github.com/mintty/wsltty/files/813188/mintty-debug.zip)

**Comment by mintty** [comment] 2017-03-02 08:54
Also, referring to https://github.com/mintty/mintty/issues/533#issuecomment-283253542,
do you happen to run conemu or any other console-related tool?

**Comment by kylemacfarlane** [comment] 2017-03-02 18:01
I did see mintty/mintty#533 but it's closed so I assumed that one had been fixed.

I don't have anything like conemu installed and it's actually a pretty fresh (1-2 weeks old) Windows install. I've been trying to see if I can survive with just a simple WSL setup.

**Comment by mintty** [comment] 2017-03-03 09:29
@valeryan, I'll provide another debug version tonight. My suspicion is that some system component or tool may have installed a Windows API hook that aborts setup of the font chooser dialog. I'll add specific diagnostics to detect that.

**Comment by mintty** [comment] 2017-03-03 19:04
Please run two test sessions with this debug version, with MINTTY_DEBUG=h and MINTTY_DEBUG=hn.
[mintty-debug.zip](https://github.com/mintty/wsltty/files/817639/mintty-debug.zip)

**Comment by valeryan** [comment] 2017-03-06 18:06
@mintty sorry I got bogged down with school work and I haven't been able to run these test for you. I see that the issue was closed do you still need me to run these test and report back? I will have time tomorrow after my finals are turned in.

**Comment by mintty** [comment] 2017-03-06 18:44
The other issue was closed as explained in https://github.com/mintty/mintty/issues/533#issuecomment-216120613. ("Closed" does not always mean "fixed" for sure.)
I think there are 2 or 3 people now reporting such problems and I'm not even sure whether they have the same symptoms because some bug reports are kind of fuzzy. I do have a suspicion what might be going on but as I cannot reproduce the symptoms, I need at least 1 person to cooperate for testing.
Tomorrow will be fine, of course, or later as it suits. Thanks for your notice.

**Comment by valeryan** [comment] 2017-03-06 19:07
Awesome, I now have two systems that are running the insider build and WSL with your mintty as my main terminal. I got permission to upgrade my work computer to insider for and experiment with WSL. Oddly enough my work computer does not have this issue. It can open the font dialog just fine. 

I feel like maybe it could be related to my home pc going through several insider builds. Who knows... If I get done with my finals at a reasonable time I will do your test other wise it will be tomorrow night.

I am always glad to help great projects that make my life better. 💯

**Comment by valeryan** [comment] 2017-03-09 02:56
Here is the debug info from h and hn

[mintty.debug.zip](https://github.com/mintty/wsltty/files/829608/mintty.debug.zip)

**Comment by mintty** [comment] 2017-03-09 06:49
Thank you; the log does not confirm my suspicion (that another hook would spoil the initialization).
Assuming that in both cases, the font chooser did not show up for you, I hardly have any more idea;
can you also retest with `-o OldFontMenu=yes` please (changed a detail there as well)?

**Comment by mintty** [comment] 2017-03-11 20:29
I'm closing this issue now as there is no evidence of a bug in mintty.
Considering to drop the Windows font chooser altogether, however, because it's repeatedly causing trouble.

**Closed by mintty** 2017-03-11 20:29 UTC

**Comment by mintty** [comment] 2017-04-13 23:24
wsltty 0.7.6 (mintty 2.7.6) should have fixed occasional hangup on Apply in font chooser.
