### ISSUE TITLE
Opening wsltty directly maximized doesn't set the terminal size

### ISSUE THREAD

**Issue by DanielCeregatti** [mintty/wsltty#73] opened 2017-11-17 20:27 UTC
Open wsltty, right click the start bar icon, right click "WSL Terminal", click properties. In the new dialog change "Run" to "Maximized", click OK. RIght click the start bar icon, click "WSL Terminal" to start a new terminal. Use any curses based app (vim, for example), and note that it's limited to a viewport the size of the default terminal (as if it hadn't been maximized):

![capture](https://user-images.githubusercontent.com/384719/32967341-2554d56e-cb92-11e7-94e1-4491489e42d7.PNG)

Exit vim, unmaximize the window, maximize it again, and run vim again. Note that everything is now fine:

![capture](https://user-images.githubusercontent.com/384719/32967370-4974a9f6-cb92-11e7-88f1-502a348ccdcc.PNG)

IMO, the proper terminal size should be set when wsltty is set to start maximized. Mintty in cygwin handles this correctly.

**Comment by mintty** [comment] 2017-11-17 21:27
This has been reported before but I cannot reproduce it. What does `stty size` say for you?

**Comment by DanielCeregatti** [comment] 2017-11-17 21:28
$ stty size
24 80

**Comment by DanielCeregatti** [comment] 2017-11-17 21:28
And after unmax/max:

$ stty size
73 271

**Comment by mintty** [comment] 2017-11-17 21:32
Here it reports a proper size (e.g. 45 172) right away.
Sure you didn't set up some particular way of invocation (right-click Start Menu doesn't seem to be correct, unless you've exchanged your mouse buttons)?

**Comment by DanielCeregatti** [comment] 2017-11-17 21:33
I have it pinned. I wrote "right click start bar icon", not start menu.

**Comment by mintty** [comment] 2017-11-17 21:41
Followed your description precisely, not reproduced.
As a workaround, use `-w max` or `-w full` in the command line instead.

**Comment by DanielCeregatti** [comment] 2017-11-17 21:43
![ezgif-4-b86c277323](https://user-images.githubusercontent.com/384719/32970265-234e986c-cb9d-11e7-8c24-c2a3ca1628b4.gif)

**Comment by DanielCeregatti** [comment] 2017-11-17 21:52
I was hoping github supported proper video, but seems it does not, and converting to animated gif makes everything too small to read. Here's the original video:

[2017-11-17 13-38-27.flv.gz](https://github.com/mintty/wsltty/files/1483939/2017-11-17.13-38-27.flv.gz)

Anyhow, adding -w max (or -w full) and resetting the drop down in the properties dialog back to "normal", (from maximized) does indeed start wsltty maximized, but stty size still shows 24 80, and the problem persists.

**Comment by DanielCeregatti** [comment] 2017-11-17 22:00
[2017-11-17 13-58-43.flv.gz](https://github.com/mintty/wsltty/files/1483963/2017-11-17.13-58-43.flv.gz)

Showing the steps performed to replicate the problem.

**Comment by DanielCeregatti** [comment] 2017-11-18 01:56
Not sure why I kept calling it start bar. Obviously I meant task bar. Sorry for the confusion.

**Comment by mintty** [comment] 2017-11-18 06:18
I have the suspicion that you have an explicit `stty rows 24 cols 80` somewhere in your startup files.
How about `grep stty ~/.profile ~/.bash* /etc/profile /etc/bash.bashrc`?

**Comment by DanielCeregatti** [comment] 2017-12-08 18:58
Sorry for not following up here. The profile is pristine. There is nothing invoking stty to set it to the rows and/or columns. Did you follow the steps in the video? I'm guessing it's something to do with running from the task bar icon.

Regardless, WSL has a showstopper that means I can't use it over cygwin, so I'm giving up on WSL. Feel free to close the bug.

**Comment by mintty** [comment] 2017-12-09 07:29
I've also checked both your videos (again) to make sure to reproduce your steps.
It behaves correctly here.

Please add `stty size` to the top of your ~/.bashrc and ~/.profile scripts. The output should appear above your "keychain" output; if it doesn't please find where that is produced and whether there is anything weird about it.

**Comment by mintty** [comment] 2017-12-16 22:22
Closing for missing evidence of a bug.

**Closed by mintty** 2017-12-16 22:22 UTC
