### ISSUE TITLE
Install scripts break if username contains '&'

### ISSUE THREAD

**Issue by TjlHope** [mintty/wsltty#213] opened 2019-12-16 11:01 UTC
I use mintty with cygwin, and was just trying out WSL (default terminal is rubbish) when I found this.

Changing the user name would be possible, but I'd prefer to avoid it if it can be easily fixed. I'm guessing this is just a variable that hasn't been quoted properly? If I get a chance later I'll have a look through the scripts myself.

(Note: I get similar problems when trying to install with chocolaty and from the releases here)

Thanks!

**Comment by mintty** [comment] 2019-12-16 11:47
I was thinking about a patch as attached.
The problem is that in cmd scripts, quoting is not handled in a very systematic way and can well result in double quoting, which will again cause trouble. Feel free to try the attached scripts (not yet tested).
If may also help to point out where exactly the current scripts fail.
[quotbat.zip](https://github.com/mintty/wsltty/files/3967827/quotbat.zip)

**Comment by mintty** [comment] 2020-03-08 10:35
Released 3.1.4.

**Comment by mintty** [comment] 2020-03-17 10:37
I'm sorry I need to revert the fix for this issue as it causes trouble elsewhere, spoiling user names with space (#230).
Since "&" in a user name is more exotic than " ", the latter has precedence. Right now, I see no fix to serve both cases because the handling of environment variables and their string values in the `set` command of cmd.exe is not very flexible. Maybe it'll be necessary to port the installer from cmd.exe to dash.exe to solve the issue.

**Comment by mastahcez** [comment] 2020-03-22 11:55
wsltty 3.1.4 breaks install even more, my user name is "C. Abińska-Kuj", I can't change it because company policy. Before it would at least copy files to appdata, now it doesn't even do that.

**Comment by mintty** [comment] 2020-04-02 13:17
Released installer 3.1.4.2, please check.

**Closed by mintty** 2020-04-02 13:17 UTC
Labels: help wanted

**Comment by oysteinkrog** [comment] 2020-05-07 10:45
Does not work for me, my username is "Øystein"

**Comment by oysteinkrog** [comment] 2020-05-07 10:50
My apologies, I had both the chocolatey version and this github release version installed. After uninstalling the choco version, it now works.
Thank you:)
