### ISSUE TITLE
Color Schemes not always switching immediately

### ISSUE THREAD

**Issue by Mastermind497** [mintty/wsltty#251] opened 2020-08-08 02:10 UTC
I have tried numerous color schemes, (many of them from base16-mintty), and most of them are rendering the same! I have tried changing numbers and values to no avail. I just reinstalled this and the issues started, never happened before.

Preinstalled Color Scheme HTML:
![image](https://user-images.githubusercontent.com/39387439/89700228-a337fb00-d8fa-11ea-8a65-b36f8c607ad0.png)

Preinstalled themes.zoo:
![image](https://user-images.githubusercontent.com/39387439/89700234-b9de5200-d8fa-11ea-87a1-18b5abbd46b8.png)

Preinstalled Mintty:
![image](https://user-images.githubusercontent.com/39387439/89700240-c5317d80-d8fa-11ea-9c47-808db9c06e48.png)

As you can see, these are all the same. Even custom color schemes do not work.

**Comment by Mastermind497** [comment] 2020-08-08 03:05
Update: It seems like after I copied a working color scheme, like nord, and retyped all of the config, it works. However, when I change the name to use the extension .minttyrc, the color scheme stops working. Is this an issue with mintty or with wsltty?

**Comment by mintty** [comment] 2020-08-08 14:05
I notice that in some cases the change is not made visible immediately but only after the windows is redisplayed, e.g. by simply moving it. Can you confirm this happens? Cause to be analysed.

**Comment by mintty** [comment] 2020-08-10 09:41
I changed the title as the themes actually work, just the feedback when switching may be delayed.
I observed delayed application when switching among themes "vga", "windows10", "xterm" on one machine, while other themes would switch immediately. I could not reproduce the issue on another machine, however, so it's still mysterious what happens.

**Comment by buiducanh** [comment] 2020-09-05 07:43
https://github.com/morhetz/gruvbox-contrib/tree/master/mintty

I used gruvbox successfully with wsltty before but with the latest release 3.30, it doesn't change color at all *if I put it under wsltty\themes\gruvbox.minttyrc*

However, if I copy the theme values into wsltty\config, the color does show up. I think there might be a bug in how wsltty load the theme values from declared themes

**Comment by mintty** [comment] 2020-09-07 07:28
There were actually two problems. Fixed display of themes with '.minttyrc' filename suffix. And ensuring screen refresh.
I'll also include the gruvbox theme if that's OK.

**Comment by mintty** [comment] 2020-10-24 15:35
Released 3.4.1.

**Closed by mintty** 2020-10-24 15:35 UTC
