### ISSUE TITLE
wsltty 3.1.4 install failing for user name with spaces

### ISSUE THREAD

**Issue by gtumbaga** [mintty/wsltty#230] opened 2020-03-16 17:48 UTC
This is the installer I am running:
`wsltty-3.1.4-install-x86_64.exe`

I am running:
Edition: Windows 10 Pro
Version: 1909
OS build: 18363.720

---

Hello.  When I try to run the installer, the installation is not successful.  I tried to debug, but the command window appears and disappears so quickly it was quite difficult.

However, from what I could tell, I think the installation is running in to problems with my Windows User directory containing a space in the name.
`C:\Users\Gabriel Tumbaga\`

Some of the errors look to be complaining about incomplete paths such as:
`C:\Users\Gabriel`
or
`Tumbaga\AppData\Local\wsltty`

which clearly looks like the space in my Username directory is causing the issue.

---

If this information helps, the previous installer `wsltty-3.1.0.2-install-x86_64.exe` is successfully able to install without issue.

**Comment by mintty** [comment] 2020-03-17 10:41
This was caused by the fix for #213 which added embedding quotes to cmd.exe environment assignments like `set installdir="%LOCALAPPDATA%\wsltty"`. It is unclear whether it is possible at all in cmd.exe to handle such assignments without the quotes for all possible cases, as characters like "&" would need to be escaped like "^&" for the assignment.
Maybe it'll be necessary to port the installer from cmd.exe to dash.exe to solve the issue for all cases.

**Comment by mintty** [comment] 2020-03-17 12:34
References:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1
https://ss64.com/nt/syntax-dequote.html
The latter may be a solution to make it work while leaving the quotes in.

**Comment by mastahcez** [comment] 2020-03-22 01:21
Same here, wish I could choose a different user name but it's company policy here that the systems are set up by administrators and they put dots, weird fonts, dashes and spaces in user names.. 
Worst case scenario is a user profile like "C:\Users\Ććć. Yyy-Żżż"

**Comment by mastahcez** [comment] 2020-03-22 22:19
Why not just install by default to somewhere safer like program files or program data?

**Comment by mintty** [comment] 2020-03-22 22:37
`Program Files` has a space as well.
Originally the idea was to install into the same domain as WSL itself, but the latter has changed meanwhile. A problem, however, would still be to install to a place that requires admin privileges to write. I'd prefer wsltty to stay user-installable for all users (well, currently all without space :( but that's to change).

**Comment by mintty** [comment] 2020-04-02 13:16
Released installer 3.1.4.2, please check.

**Closed by mintty** 2020-04-02 13:16 UTC
Labels: help wanted

**Comment by gtumbaga** [comment] 2020-04-02 16:30
Confirmed, I have just successfully installed with the `wsltty-3.1.4.2-install-x86_64.exe` on Windows 10, v 1909
