### ISSUE TITLE
Problems with Aero snap

### ISSUE THREAD

**Issue by erantapaa** [mintty/wsltty#80] opened 2017-12-27 18:51 UTC
Steps to reproduce:

1. Launch a new medium sized WSL terminal - e.g. 80 cols by 24 rows
2. Use Windows Aero snap to have the window occupy the left half of the screen (drag title bar to left edge)
3. Use Ctrl-Shift right click and select the current session

Effect: The window is resized to its original size and the text is a lot smaller.

FWIW, I'm using the Ubuntu Monospace font, 14pt.

**Comment by mintty** [comment] 2018-01-03 20:37
The font size is only scaled down if you hold the Shift key when you click-select the session.
It's a consequence of "Shift-coupled font-with-window zooming" (see the manual page) and that's a feature, not a bug. If you don't want that, release Shift before the click.

**Comment by mintty** [comment] 2018-01-03 20:38
Another question is whether the window should be restored to previous size if selected. I'll check whether that can easily be changed. On the other hand, why would you reselect the active session at all?

**Comment by mintty** [comment] 2018-01-03 20:54
In fact, the target window is set to "RESTORE" on purpose, in case it was minimized (iconic).
A guard can be added to checked whether it was actually iconic.

**Comment by erantapaa** [comment] 2018-01-04 22:20
> On the other hand, why would you reselect the active session at all?

I was just simplifying the test procedure.

I see that releasing the SHIFT key before selecting a session does not change the font size.

However it would be nice if the session did not get resized when you selected it through the CRTL-SHIFT-RIGHT click menu. It seems that the mintty window doesn't remember that it was resized by Aero.

mintty doesn't have tabs, but it almost has that capability with multiple sessions. It would be really nice to be able to quickly flip between the multiple sessions.  Hot keys would be the preferable way to do this, e.g. move to the next/prev session.

**Comment by mintty** [comment] 2018-01-04 22:41
Yes, the window does not get resized anymore; fixed in the mintty repository.
Hot keys are available: Ctrl+TAB, Ctrl+Shift+TAB.

**Comment by mintty** [comment] 2018-01-08 21:23
Released 1.8.3.

**Closed by mintty** 2018-01-08 21:23 UTC
